version: "3"

services:
  news-database:
    container_name: "news_database"
    image: "postgres:13-alpine"
    restart: "unless-stopped"
    ports:
      - "7432:5432"
    networks:
      - "news_network"
    environment:
      POSTGRES_PASSWORD: "newspassw0rd"
      POSTGRES_USER: "newsuser"
      POSTGRES_DB: "newsdb"

  news_service:
    container_name: "news_service"
    restart: "unless-stopped"
    build:
      context: "./news-service"
      dockerfile: Dockerfile.dev
    networks:
      - news_network
    ports:
      - "3035:3035"
    volumes:
      - "./news-service:/var/www/news-service"
    environment:
      DB_HOST: "news_database"
      DB_NAME: "newsdb"
      DB_SCHEMA: "public"
      DB_PORT: "5432"
      DB_USER: "newsuser"
      DB_PASSWORD: "newspassw0rd"
      JWT_SECRET: "ASdas7d9132sjdfsdlfkgfhfg4872"
      JWT_ACCESS_EXPIRES_IN: "3m"
      JWT_REFRESH_EXPIRES_IN: "3d"

networks:
  news_network:
    external: False
